// priority: 95

global.UTD = global.UTD || {};

(function () {
  var utd = global.UTD;
  utd.assetStatusManifest = {
    "catalog_hash": "c0728a591dfa8581",
    "content_fingerprint": "c0728a591dfa8581",
    "counts": {
      "cycles": 0,
      "dependencyItems": 2,
      "issues": 0,
      "lootPolicies": 1,
      "managedItems": 2,
      "recipes": 1
    },
    "deployed_hash": null,
    "generated_at": "2026-07-11T00:00:00Z",
    "items": [
      {
        "asset_key": "zombiekit:baseball_bat",
        "canonical_components": {
          "canonical": "",
          "encoding": "utd-nbt-canonical-v1",
          "snbt": "{}"
        },
        "canonical_variant": null,
        "catalog_hash": "3f84c21cfe69a445",
        "catalogued": true,
        "client_name_zh_cn": "实木棒球棍",
        "components_canonical": "",
        "components_snbt": "{}",
        "deployed_hash": null,
        "human_selected": true,
        "identity_components_canonical": "",
        "identity_kind": "item",
        "issues": [],
        "item_key": "zombiekit:baseball_bat",
        "loot_enabled": false,
        "loot_level": null,
        "managed": true,
        "recipe_input": false,
        "recipe_input_count": 0,
        "recipe_output": true,
        "recipe_output_count": 1,
        "registry_id": "zombiekit:baseball_bat",
        "stale": false,
        "sync": "local_only",
        "sync_state": "local_only",
        "translation_key": "item.zombiekit.baseball_bat",
        "variant_discriminator": "",
        "variant_key": null
      },
      {
        "asset_key": "sample:fpe-energy-a",
        "canonical_components": {
          "canonical": "firstpersonfoodeating_profile.food_id=firstpersonfoodeating:i_bang_a",
          "encoding": "utd-nbt-canonical-v1",
          "snbt": "{firstpersonfoodeating_profile:{food_id:\"firstpersonfoodeating:i_bang_a\"}}"
        },
        "canonical_variant": null,
        "catalog_hash": "6a3db5ab2d18c9f8",
        "catalogued": true,
        "client_name_zh_cn": "高能量棒",
        "components_canonical": "firstpersonfoodeating_profile.food_id=firstpersonfoodeating:i_bang_a",
        "components_snbt": "{firstpersonfoodeating_profile:{food_id:\"firstpersonfoodeating:i_bang_a\"}}",
        "deployed_hash": null,
        "human_selected": true,
        "identity_components_canonical": "food_id=firstpersonfoodeating:i_bang_a",
        "identity_kind": "components",
        "issues": [],
        "item_key": "sample:fpe-energy-a",
        "loot_enabled": true,
        "loot_level": 1,
        "managed": true,
        "recipe_input": false,
        "recipe_input_count": 0,
        "recipe_output": false,
        "recipe_output_count": 0,
        "registry_id": "firstpersonfoodeating:pack_food",
        "stale": false,
        "sync": "local_only",
        "sync_state": "local_only",
        "translation_key": "item.firstpersonfoodeating.pack_food",
        "variant_discriminator": "food_id=firstpersonfoodeating:i_bang_a",
        "variant_key": "food-a"
      },
      {
        "asset_key": "minecraft:oak_slab",
        "canonical_components": {},
        "canonical_variant": null,
        "catalog_hash": "661d2e32923c2c8b",
        "catalogued": false,
        "client_name_zh_cn": "Oak Slab",
        "components_canonical": "",
        "components_snbt": "",
        "deployed_hash": null,
        "human_selected": false,
        "identity_components_canonical": "",
        "identity_kind": "item",
        "issues": [],
        "item_key": "minecraft:oak_slab",
        "loot_enabled": false,
        "loot_level": null,
        "managed": false,
        "recipe_input": true,
        "recipe_input_count": 1,
        "recipe_output": false,
        "recipe_output_count": 0,
        "registry_id": "minecraft:oak_slab",
        "stale": false,
        "sync": "local_only",
        "sync_state": "local_only",
        "translation_key": "",
        "variant_discriminator": "",
        "variant_key": null
      },
      {
        "asset_key": "zombiekit:iron_wire",
        "canonical_components": {},
        "canonical_variant": null,
        "catalog_hash": "5d93659b88924fa1",
        "catalogued": false,
        "client_name_zh_cn": "Iron Wire",
        "components_canonical": "",
        "components_snbt": "",
        "deployed_hash": null,
        "human_selected": false,
        "identity_components_canonical": "",
        "identity_kind": "item",
        "issues": [],
        "item_key": "zombiekit:iron_wire",
        "loot_enabled": false,
        "loot_level": null,
        "managed": false,
        "recipe_input": true,
        "recipe_input_count": 1,
        "recipe_output": false,
        "recipe_output_count": 0,
        "registry_id": "zombiekit:iron_wire",
        "stale": false,
        "sync": "local_only",
        "sync_state": "local_only",
        "translation_key": "",
        "variant_discriminator": "",
        "variant_key": null
      }
    ],
    "project_id": "utd_workbench_sample",
    "schema_version": "utd-asset-status/v1"
  };
})();
